### ISSUE TITLE
ox.plot_graph() fails with attribute error

### ISSUE THREAD

**Issue by philippschw** [gboeing/osmnx#40]
I noticed now when upgrading osmnx that suddenly: ox.plot_graph() fails with attribute error.
The problematic function is in line 261 of  plot.py:  "ax.set_facecolor()".

Code looks like this:
```

# create the figure and axis
fig, ax = plt.subplots(figsize=(fig_width, fig_height), facecolor=bgcolor)
ax.set_facecolor(bgcolor)
```

Produces the following error:
AttributeError: 'AxesSubplot' object has no attribute 'set_facecolor'

For now I just outcommented the problematic, which seem to have fixed it.
Problem occurs on ubuntu and osmnx version - osmnx-0.4-py27, today installed from conda forge.

Before in older osmnx version it was working well with: 
```
    # create the figure and axis
    fig, ax = plt.subplots(figsize=(fig_width, fig_height), facecolor=bgcolor)
    ax.set_axis_bgcolor(bgcolor)
```
But the set_axis_bgcolor function was deprecated in version 2.0

**Comment by gboeing** [comment]
See #39 

In particular the comment https://github.com/gboeing/osmnx/issues/39#issuecomment-285132072

OSMnx v0.4 upgraded its plotting functions to work with the new mpl 2.0 API and is not backwards-compatible with mpl 1.x: https://github.com/gboeing/osmnx/blob/b29eea6dcd38b161e890f61d76f8567ec7f616bf/setup.py#L57

**Comment by philippschw** [comment]
thanks for your quick reply!
However, I am using matplotlib 2.0.0 and though. your short test code runs fine, the attribute error with osmnx occurs.

**Comment by gboeing** [comment]
Strange. So, matplotlib can access `ax.set_facecolor` from your script, but it can't access it when OSMnx calls it? It seems like there *must* be a versioning issue here. I hate to flog a dead horse but is there any chance you are not using mpl 2.x + OSMnx 0.4 interactively in your script?

**Comment by gboeing** [comment]
@philippschw any update on this?

**Comment by ptitjano** [comment]
Hi,

For a matplotlib 1.x compatibility, one could add in plot.py  something like: 
```python
import matplotlib as mpl
if int(mpl.__version__[0]) <= 1:
        ax.set_axis_bgcolor(bgcolor)
else:
        ax.set_facecolor(bgcolor)
```

My 2 cents,
